name: Convert Model
on:
  push:
  workflow_dispatch:
jobs:
  Convert-Model:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Download CKPT
       run: |
            CKPT="https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt"
            curl $CKPT -o Model.ckpt
            du -sh Model.ckpt
     - name: Install conda
       run: brew install --cask anaconda && brew --prefix anaconda
     - name: Convert Model
       run: |
            curl https://raw.githubusercontent.com/mortenjust/maple-diffusion/main/Converter%20Script/maple-convert.py > maple-convert.py
            conda deactivate
            conda remove -n native-diffusion --all
            conda create -n native-diffusion python=3.10
            conda activate native-diffusion
            pip install torch typing_extensions numpy Pillow requests pytorch_lightning
            ./native-convert.py Model.ckpt

            zip -r9 Model.zip bins
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add Model.zip
            git commit -m "Model"
            git push
